### ISSUE TITLE
evaluate_objective.m doubt

### ISSUE THREAD

**Issue by GYengera** [david-m-rosen/SE-Sync#1]
Sir,

In the computation of `trQYtY` in the file evaluate_objective.m, should it be equal to `trQYtY = trace(YQ * Y)` instead of `trQYtY = trace(YQ * Yt)` ?

**Comment by david-m-rosen** [comment]
Hi Gaurav,

This function exploits the cyclic property of the trace (https://en.wikipedia.org/wiki/Trace_(linear_algebra)#Basic_properties) to write tr(Q * Y^T  * Y) = tr(Y * Q * Y^T) = tr( (Y*Q) * Y^T).  The advantage of the last form is that it only involves products in which at least one of the matrices is no larger than Y; since Y has a very small row-dimension (typically ~5), these can be evaluated efficiently.  In contrast, the product Q * Y^T * Y is a (dense) matrix of the same size as Q, which is **much** larger than Y; indeed, trying this even on a moderately-sized problem actually crashes my desktop :-P.

**Comment by GYengera** [comment]
That clears my doubt. Thank you.
