### ISSUE TITLE
Compiling on macOS

### ISSUE THREAD

**Issue by StephenMcGill-TRI** [david-m-rosen/SE-Sync#10]
Hello,

I'm not sure if macOS is a target platform, but I wanted to post a single line tweak, if it seems ok!

The following tweak seems to be required to build:
Adding `#include <random>` to `SESync_utils.h`

The following bash commands replicate the build on 10.13.4:
```bash
brew install llvm@4
cd C++
mkdir build
cd build
env CC=$(which clang) CXX=$(which clang++) cmake ..
make
```

Thank you!

**Comment by david-m-rosen** [comment]
Hey Stephen!

Thanks for bringing this to my attention (h/t also @strasdat ) -- looks like the problem may have been due to a forgotten <random> inclusion in SESyncProblem.cpp (which itself includes SESync_utils.h).

I've just pushed a commit adding this in -- would you please let me know if this resolves the problem?

Thanks!

**Comment by StephenMcGill-TRI** [comment]
Hi David,
I just pulled the code and was able to compile properly. Thanks so much for the quick response!
