### ISSUE TITLE
Synchronizing 2D rotations in 3D space

### ISSUE THREAD

**Issue by hrheydarian** [david-m-rosen/SE-Sync#13]
Hi,

I am still playing around your nice work. 

In the following code (MATLAB), I generated multiples of 2pi/4 as the absolute rotation angles around z axis with translation vector of all zero (actually 2D rotations but embedded in 3D matrices). Then, I computed the relative rotations of all pairs which results in 28 edges.

By using your library I expect to get those absolute rotations around the z axis as in this experiment there is no measurement noise. However, if you run the code, you will notice that the results are totally different with what is expected (the rotations are no longer around z axis).

If I redo the same experiment in 2D (xhat.R are 2xn and xhat.t are 2xn), I can exactly reproduce the ground-truth absolute angles.

Could you please tell me what is wrong here?

     % generate 8 angles spaced at multiples of 2pi/8
     step = 0:7;
     absAngD = step * 45;    % absolute angles (ground-truth)
     N = numel(step); 
     
     % compute relative orientations
     k=1;
     for i=1:N-1
         for j=i+1:N
             
             measurements.edges(k,:) = [i j];
             measurements.R{k} = rotz(absAngD(i) - absAngD(j));  % relative angles
             measurements.t{k} = [0;0;0];
             measurements.kappa{k} = 1;
             measurements.tau{k} = 1;
             k = k+1;
             
         end
     end
     
     %% SE3-Sync
     
     num_poses = max(max(measurements.edges));
     d = length(measurements.t{1});
     
     % Set Manopt options (if desired)
     Manopt_opts.tolgradnorm = 1e-2;  
     Manopt_opts.rel_func_tol = 1e-5; 
     Manopt_opts.miniter = 1;  
     Manopt_opts.maxiter = 300;  
     Manopt_opts.maxinner = 500; 
     
     % Set SE-Sync options (if desired)
     SE_Sync_opts.r0 = 5;  
     SE_Sync_opts.rmax = 10;  
     SE_Sync_opts.eig_comp_rel_tol = 1e-4;  
     SE_Sync_opts.min_eig_lower_bound = -1e-3;
     SE_Sync_opts.Cholesky = false;  
     
     use_chordal_initialization = true;  
     
     % Run SE-Sync
     
     % Pass explict settings for SE-Sync and/or Manopt, and use chordal
     % initialization
     fprintf('Computing chordal initialization...\n');
     R = chordal_initialization(measurements);
     Y0 = vertcat(R, zeros(SE_Sync_opts.r0 - d, num_poses*d));
     [SDPval, Yopt, xhat, Fxhat, SE_Sync_info, problem_data] = SE_Sync(measurements, Manopt_opts, 
     SE_Sync_opts, Y0);
     
     %% extract the final absolute rotation axes and angles
     for i=1:N
        curR = xhat.R(:,3*(i-1)+1:3*(i-1)+3);
        axangles(i,1:4) = rotm2axang(curR);
     end

**Comment by david-m-rosen** [comment]
Hi Hamidreza,

Thanks for your kind note, and your interest in the project :-).

When running your example script above, I obtain the following output:

```
========== SE-Sync ==========

ALGORITHM SETTINGS:

SE-Sync settings:
 Initial level of Riemannian Staircase: 5
 Final level of Riemannian Staircase: 10
 Maximum number of iterations to perform for minimum eigenvalue computation in test for positive semidefiniteness: 2000 [default]
 Tolerance for accepting an eigenvalue as numerically nonnegative in optimality verification: 0.0001 [default]
 Using QR decomposition to compute orthogonal projection
 Initialization method: chordal [default]

Manopt settings:
 Stopping tolerance for norm of Riemannian gradient: 0.01
 Stopping tolerance for relative function decrease: 1e-05
 Maximum number of Hessian-vector products to evaluate in each truncated Newton iteration: 500
 Minimum number of trust-region iterations: 1
 Maximum number of trust-region iterations: 300
 Using incomplete zero-fill Cholesky preconditioner for truncated conjugate gradient inexact Newton step computations [default]


INITIALIZATION:

Constructing auxiliary data matrices from raw measurements...
Constructed rotational connection Laplacian in 0.017423 seconds
Constructed oriented incidence matrix in 0.002216 seconds
Constructed translational observation and measurement precision matrices in 0.026108 seconds
Constructed Laplacian for the translational weight graph in 0.000718 seconds
Computed lower-triangular factor of reduced translational weight graph Laplacian in 0.000369 seconds
Caching additional product matrices ... 
Auxiliary data matrix construction finished.  Elapsed computation time: 0.069383 seconds

Constructing incomplete Cholesky preconditioner... Elapsed computation time: 0.00158 seconds

Using user-supplied initial point Y0 in Riemannian Staircase


Solving Riemannian optimization problems using Manopt's "trustregions" solver


RIEMANNIAN STAIRCASE (level r = 5):
                                            f: -8.904894e-16   |grad|: 6.251847e-15
Gradient norm tolerance reached; options.tolgradnorm = 0.01.
Total time is 0.059678 [s] (excludes statsfun)

Checking second-order optimality...
Found second-order critical point! (minimum eigenvalue = 3.55271e-15, elapsed computation time 0.178369 seconds)


===== END RIEMANNIAN STAIRCASE =====

Rounding solution...
Elapsed computation time: 0.012343 seconds

Recovering translational estimates...
Elapsed computation time: 0.001798 seconds

Value of SDP solution F(Y): -8.90489e-16
Norm of Riemannian gradient grad F(Y): 6.25185e-15
Value of rounded pose estimate xhat: -2.19813e-15
Suboptimality bound of recovered pose estimate: -1.30764e-15

Total elapsed computation time: 0.452736 seconds


===== END SE-SYNC ===== 

```
The key line in this output is:

`Value of rounded pose estimate xhat: -2.19813e-15
`

meaning that SE-Sync has found a solution with (numerically) 0 error (i.e., one that agrees _exactly_ with the measurements, as expected). 

As you observed, my solution is also comprised of rotational estimates that do not correspond to rotation around the z-axis, as can be seen, for example, by printing out the first rotation matrix R1:

```
>> xhat.R(:, 1:3)

ans =

     0     0    -1
    -1     0     0
     0     1     0
```
So, how can this be?  The issue here is that the estimation problem that SE-Sync solves (Problem 1 in the tech report) does not have a unique solution; in fact it has _infinitely many solutions_, as can be seen by observing that, since the only quantities that actually appear in Problem 1's loss function are _relative_ transforms of the form x_i^-1 * x_j, then if x* = (x_1*, ..., x_n*) is any optimal solution of Problem 1, we can generate an _entire set_ of equivalent solutions simply by left-multiplying each component x_i* of  x* by some element g from SE(d), since then (gx_i*)^-1  * (gx_j*) = x_i*^-1 * g^-1 * g  x_j* = x_i*^-1 * x_j*, (in words, this operation leaves the _relative_ transforms x_i*^-1 * x_j* between each pair of elements x_i* and x_j* in the original solution x* unchanged, since the factors of g cancel, and therefore the transformed solution g * x^* "looks the same" to Problem 1's objective as does x^* -- see footnote 8 after equation (11) in the tech report).  

Physically, this simply corresponds to the fact that the world does not have a single preferred, absolute coordinate system.  In the example that I described above, x^* and g * x^* actually represent the _same_ map (in the sense that the _relative_ transforms between corresponding pairs of poses (i,j) are the same in both cases), but expressed in _different coordinate systems_ (with g being exactly the transform that relates these two systems).

So, is it the case, then, that the solution found by SE-Sync really is the "same" solution as the one containing only rotations around the z-axis?  Or more generally:  how can we tell if two solutions x and y for Problem 1 actually represent the "same" map, given that they might be expressed in _different_ coordinate systems?  This problem was precisely the one that motivated the discussion in Appendix C.1.  In that section, we describe a notion of distance (_orbit distance_, cf. equations (106) and (107)) that measures the dissimilarity between two points x and y in a way that is able to account for the fact that x and y may be expressed in _different coordinate systems_.  Furthermore, in Theorem 5, we describe how one can compute this distance in practice, together with the optimal registration g that transforms y into the frame in which x is expressed.  

Here's how this computation looks for the problem at hand:

```
% Compute orbit distance between Rz (set of ground-truth rotational
% states, expressed as rotations around the z-axis) and R (SE-Sync's
% rotational solutions)

n = 8;
d = 3;
Rz = zeros(d, d*n);
for k = 0:n-1
    Rz(1:3, 3*k + 1 : 3*k + 3) = rotz(-45*k);
end
 
R = xhat.R;
 
% Compute orbit distance d_S(Rz, R) and optimal registration G_S as 
% described in Theorem 5 in the tech report
 
[U, Sigma, V] = svd(Rz * R');
Xi = diag([1, 1, det(U*V')]);
 
d_S = sqrt(2*d*n - 2 * trace(Xi * Sigma))
 
% Compute optimal registration sending R to Rz's coordinate frame
G_S = U * Xi * V'
 
% Register SE-Sync solution R in Rz's coordinate frame
R_reg = G_S * R
```

which produces the output:

```
d_S =

     0


G_S =

         0   -1.0000    0.0000
    0.0000    0.0000    1.0000
   -1.0000         0    0.0000


R_reg =

  Columns 1 through 8

    1.0000    0.0000         0    0.7071    0.7071    0.0000   -0.0000    1.0000
   -0.0000    1.0000   -0.0000   -0.7071    0.7071    0.0000   -1.0000   -0.0000
         0    0.0000    1.0000   -0.0000    0.0000    1.0000   -0.0000         0

  Columns 9 through 16

         0   -0.7071    0.7071         0   -1.0000    0.0000    0.0000   -0.7071
   -0.0000   -0.7071   -0.7071   -0.0000   -0.0000   -1.0000    0.0000    0.7071
    1.0000   -0.0000    0.0000    1.0000   -0.0000    0.0000    1.0000    0.0000

  Columns 17 through 24

   -0.7071    0.0000    0.0000   -1.0000         0    0.7071   -0.7071   -0.0000
   -0.7071   -0.0000    1.0000    0.0000   -0.0000    0.7071    0.7071   -0.0000
   -0.0000    1.0000    0.0000         0    1.0000    0.0000    0.0000    1.0000

```
So in fact, SE-Sync _did_ recover your ground-truth rotations, just expressed in a different coordinate system :-).
