### ISSUE TITLE
add prior constraint

### ISSUE THREAD

**Issue by weisongwen** [david-m-rosen/SE-Sync#18]
@david-m-rosen  Thanks for your great work. is it possible to add prior constraint (in this case, the optimization is formulated as a MAP-maximum a posterior problem)?

Best,
Weisong,

**Comment by david-m-rosen** [comment]
Hey @weisongwen!  

I assume you mean (unary) priors on individual poses?  If so, then you're in luck :-)!  It is actually possible to express these priors directly in the model that SE-Sync already employs: you can simply introduce a single distinguished pose x_w that represents the "world" coordinate system that you want to use, and then express priors as relative measurements against x_w.  To transform the estimates returned by SE-Sync back into this distinguished world frame when you're done, you'll then just need to multiply everything by x_w^{-1}, where x_w is the estimate for the "world" pose returned by SE-Sync.

Note that while this construction may at first glance appear somewhat contrived, it's actually a straightforward mathematical  reflection of the fact that *there is no such thing as an "absolute" coordinate system*.  That is, even when we are using measurements that we typically *think of* as "absolute" (e.g. GPS measurements of position), what we are *actually* doing is measuring position *relative to* a commonly-adopted "standard" reference frame (in the case of GPS measurements, the lines of latitude and longitude that are laid out on the surface of the Earth).  The construction that I described above simply expresses this fact in a more concrete way than we typically do :-).

**Comment by david-m-rosen** [comment]
Closing this issue, as I've not heard anything further.

**Comment by weisongwen** [comment]
@david-m-rosen , Thanks for your detailed reply and sorry for my late reply. I am still looking into the algorithm as it is really quite tough to fully understand. I will let you know if I have any updates based on your comments. :-)

**Comment by david-m-rosen** [comment]
Hey @weisongwen,

No worries -- I just want to stay on top of any reported issues to keep the repo in good working order :-).

A couple of additional comments that might help to clarify the discussion:
- The construction that I outlined in my previous post (for encoding unary priors in a particular coordinate frame using _relative_ constraints) actually has nothing to do with the SE-Sync algorithm itself: this is ultimately just a statement about what it means to transform between different coordinate frames.  So one shouldn't need to dig into the guts of the SE-Sync algorithm itself to understand this construction :-). <br/>

- While some of the math involved in _deriving_ the SE-Sync algorithm is admittedly perhaps a bit exotic, the actual _algorithm_ itself turns out not to be very different from "standard" pose-graph SLAM.  One way to see this is by comparing Problems 3 and 9 in the paper.  Problem 3 is equivalent to a totally standard formulation of pose-graph SLAM (my colleague Kasra Khosoussi has a  very nice [paper](https://opus.lib.uts.edu.au/bitstream/10453/36699/1/rss15final.pdf) that investigates this form of the problem in more detail, including how to find (local) solutions of it using standard NLS libraries like e.g. GTSAM and g2o).  Problem 9 is the optimization problem that SE-Sync actually uses to search for _global_ solutions.  If you compare Problem 3 and Problem 9, you'll see that the only difference between these two problems is that Problem 9 replaces the original rotation variables Ri in SO(d) with elements Yi from the Stiefel manifold St(d,r), which is just a higher-dimensional manifold containing SO(d) itself.  So all we're really doing in passing from Problem 3 to Problem 9 is giving ourselves a _bit_ more room to move around in the search space, in order to avoid becoming stuck in bad local minima.  So 90% of what SE-Sync is doing is just solving a (slightly) higher-dimensional generalization of "standard" pose-graph SLAM :-).  [As an aside: this is also why SE-Sync is so fast, especially compared to prior approaches for _global_ optimization: the subproblems that it's solving are _very_ close to the "standard" problem that current state-of-the-art _local_ search methods like GTSAM solve, and so we can achieve comparable numerical performance -- in fact, **_better_** performance if we're a bit more clever about designing the optimization method in the right way :-)].    This is really the core idea of the method.  The rest of the paper is just devoted to (1) proving that this approach will actually succeed in finding the right answer, and (2) deriving a condition that one can check to determine whether a given critical point for Problem 9 is a global solution (so we can stop), or whether we need to keep searching.

Hope this helps :-)!

**Comment by weisongwen** [comment]
Hi @david-m-rosen , Many thanks for your detailed explanation. Based on your explanation, my understanding is that: a higher-dimensional manifold is employed for searching in SE-Sync to approach the global optimal. I highly believe that your work can have a pretty deep impact on the state estimation field. 

Currently, I am doing collaborative positioning based on camera, imu, GNSS, and inter-ranging measurements from multiple agents. I will try to compare your SE-Sync to this case. I will let you know if I got any interesting findings,

Thanks a lot :-)
Weisong,

**Comment by david-m-rosen** [comment]
Hey @weisongwen,

That's the right intuition.  If you'd like an alternative take on this, you might also be interested in checking out the [video](https://www.youtube.com/watch?v=5ppaqMyHtE0&feature=youtu.be) for our recent [paper](https://arxiv.org/abs/2008.02737) that shows how to adapt the SE-Sync approach to solve rotation averaging problems using GTSAM -- it has some nice visualizations in it that attempt to convey what the algorithm is doing a bit more transparently :-).

And please do keep me posted on the project!  It's always super fun to see how folks are using this :-).

**Comment by weisongwen** [comment]
@david-m-rosen , Many thanks for your video and paper link. This is really very very interesting. 

Sure, I will keep you updated！

Best，
Weisong,
